### ISSUE TITLE
No Access G.A.M.E API button found in game app

### ISSUE THREAD

**Issue by Nfnqqq** [Virtual-Protocol/virtuals-python#5]
![image](https://github.com/user-attachments/assets/f993dbd1-d3b4-4201-92a1-8dde33407164)

Just as you see, there is no section for API key creation, like the instruction in the notion page or the README

**Comment by nativ3ai** [comment]
no fix yet, maybe available once agent is held by address logged in.

**Comment by OnziDreox** [comment]
if you are using GAME LITE version, you wont get API key, we are working to make that available for public who does not have an agent with Virtuals
